# Generated by Django 2.1.7 on 2019-02-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutortial_title',
            new_name='tutorial_title',
        ),
    ]
